name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Build
        run: odin build . -out:snake

      - uses: actions/upload-artifact@v4
        with:
          name: snake-linux
          path: snake

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: odin build . -out:snake.exe

      - uses: actions/upload-artifact@v4
        with:
          name: snake-windows
          path: snake.exe
